services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: josh
      MONGO_INITDB_ROOT_PASSWORD: Nathan816!
    volumes:
      - ./data/db:/data/db

